//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentOfCommerceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addresses()
        {
            this.ProductSuppliers = new HashSet<ProductSuppliers>();
            this.Recipients = new HashSet<Recipients>();
        }
    
        public int id { get; set; }
        public int countryId { get; set; }
        public int cityId { get; set; }
        public int streetId { get; set; }
        public int buildingId { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Streets Streets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSuppliers> ProductSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipients> Recipients { get; set; }
    }
}
