//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentOfCommerceProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<LegalEntityTypes> LegalEntityTypes { get; set; }
        public virtual DbSet<ProductionTypes> ProductionTypes { get; set; }
        public virtual DbSet<ProductSuppliers> ProductSuppliers { get; set; }
        public virtual DbSet<Recipients> Recipients { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
        public virtual DbSet<TypesLists> TypesLists { get; set; }
    }
}
