//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentOfCommerceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesLists
    {
        public int id { get; set; }
        public int productTypeId { get; set; }
        public int supplierId { get; set; }
    
        public virtual ProductionTypes ProductionTypes { get; set; }
        public virtual ProductSuppliers ProductSuppliers { get; set; }
    }
}
